# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2f900ae95d49c67df34643ee395ef0d97d2ee76589b0171c63864088fd2acb3985199663c7b026af942a2a499c87d6c7d0b7900e3730f522f278f37cd3260f6

test:
  secret_key_base: 142875036ee0e9353a747f4fcb9149b1af0f7370de7c2a210d54e57373c31c8e89dd94d771c2f5d643006866f79eeb3f1981e6355a7b853cc6d78a02f8578df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
